version: "3.7"

services:

  space-explorer.rdok.dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - GRAPHQL_API_URL
    ports:
      - "${VIRTUAL_PORT}:80"


networks:
  default:
    external:
      name: nginx-proxy
