#!/bin/sh

docker run --rm -it \
    --publish 3000:3000 \
    --volume $(pwd):/app \
    --workdir /app \
    --user $(id -u) \
    --network node \
    --env-file .env \
    node:12-alpine \
    npm $@
