#!/bin/sh

docker run --rm -it \
    --name api-container \
    --publish 4000:4000 \
    --volume $(pwd):/app \
    --workdir /app \
    --user $(id -u) \
    --network node \
    node:12-alpine \
    npm $@
