name: Build React
on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches: master
defaults:
  run:
    working-directory: react
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn  test
