name: Deploy react
on:
  push:
    branches: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn  test
    - run: CI=true yarn build
    - run: git add --all && git commit -m 'Publish new build.'
    - run: git push origin gh-pages
